WIFI_IFACE=wlp1s0
INTERNET_IFACE=enp3s0f3u2
SSID=MyHotspot
PASSPHRASE=change-me-please
SHARE_METHOD=nat
CHANNEL=36
FREQ_BAND=5
COUNTRY=IN
IEEE80211N=1
IEEE80211AC=1
HT_CAPAB=[HT40+]
GATEWAY=192.168.12.1
DHCP_DNS=gateway
